src/core/units/Building.java, src/core/units/City.java, src/core/units/Port.java
Solve the issue of clone method and remove the belonging variable in buildings
=> Change the clone method city

src/core/actions/unitactions/Attack.java, src/core/actors/Tribe.java, src/core/actors/units/Unit.java, src/core/game/Board.java
When a unit is killed in Attack it now adds to the tribe killed units array
When an attack is finished and the unit is of a melee type it now moves to the target position
Added isKilled boolean to Unit
=> Added array for managing killed units.

src/core/actions/unitactions/Attack.java
Target unit now given appropriate buffs if now in city border limits
=> Completed Issue #72

src/core/TribesConfig.java, src/core/Types.java, src/core/actions/unitactions/Attack.java, src/core/actions/unitactions/Capture.java, src/core/actions/unitactions/Convert.java, src/core/actions/unitactions/Disband.java, src/core/actions/unitactions/Examine.java, src/core/actions/unitactions/HealOthers.java, src/core/actions/unitactions/Move.java, src/core/actions/unitactions/Recover.java, src/core/actions/unitactions/Upgrade.java, src/core/actions/unitactions/factory/AttackFactory.java, src/core/actions/unitactions/factory/CaptureFactory.java, src/core/actions/unitactions/factory/ConvertFactory.java, src/core/actions/unitactions/factory/DisbandFactory.java, src/core/actions/unitactions/factory/HealOthersFactory.java, src/core/actions/unitactions/factory/MoveFactory.java, src/core/actions/unitactions/factory/UnitActionBuilder.java, src/core/actors/units/Unit.java, src/core/game/Board.java
Also, renaming some functions for clarity. setStatus now sets if without checks.
=> Playing with turn status, making it consistent across units and actions

src/core/Constants.java, src/utils/GUI.java, src/utils/GameView.java, src/utils/InfoView.java, src/utils/TechView.java, src/utils/TribeView.java
Scaling all sizes to screen size.
=> GUI Updates 7

src/core/Constants.java, src/core/Types.java, src/core/actions/unitactions/Examine.java, src/core/game/Game.java, src/players/ActionController.java, src/utils/GUI.java, src/utils/GameView.java
- Examine action effect displayed in GUI [issue #137]
- Ports brought back (or docks) [issue #138]
=> GUI Updates 9

src/core/actions/cityactions/Build.java, src/core/actions/cityactions/Destroy.java, src/core/actions/cityactions/LevelUp.java, src/core/actions/unitactions/Attack.java, src/core/actions/unitactions/Capture.java, src/core/actions/unitactions/Examine.java, src/core/actions/unitactions/Move.java, src/core/actors/City.java, src/core/actors/Tribe.java, src/core/game/Board.java, src/core/game/GameState.java, src/core/game/LevelLoader.java
=> Fix isssues #129 and #131

src/core/Constants.java, src/core/Types.java, src/core/actions/cityactions/Spawn.java, src/utils/GUI.java, src/utils/InfoView.java, src/utils/TechView.java
- All technology requirements in Types for buildings, units, actions and resources
- GUI cross platform look and feel enabled
- Tech view displays tech tree (horizontally)  
- Tech view buttons all enabled and colour coded (blue researched, green researchable, gray unavailable)
- InfoView displays selected tech information: effect (based on building, unit, action and resource tech requirements) + requirements of parent tech and stars (overwrites info from highlight)
- Button to research tech now displayed in the action button panel underneath InfoView, enabled/disabled based on selected tech
TODO:
=> GUI technology display updates

src/utils/GameView.java, src/utils/InfoView.java
- Bugfix build action
- City borders drawing fixed, using city tile IDs
=> GUI Updates 10

src/core/actions/unitactions/Attack.java, src/core/actors/units/Archer.java, src/core/actors/units/Battleship.java, src/core/actors/units/Boat.java, src/core/actors/units/Catapult.java, src/core/actors/units/Defender.java, src/core/actors/units/Knight.java, src/core/actors/units/MindBender.java, src/core/actors/units/Rider.java, src/core/actors/units/Ship.java, src/core/actors/units/SuperUnit.java, src/core/actors/units/Swordman.java, src/core/actors/units/Unit.java, src/core/actors/units/Warrior.java, src/core/game/Board.java, src/core/game/GameState.java
GameState.killUnit: new method to refactor killing units. It's possible that isKilled flag can be removed altogether. Check if dying by retaliation attack works fine before doing so.
=> Updated isKilled flag method accessors.

src/core/actors/Tribe.java, src/core/game/Game.java, src/utils/GUI.java, src/utils/TribeView.java
Now showing properly in the GUI.
=> Update of the total production

src/Play.java, src/core/TechnologyTree.java, src/core/TribesConfig.java, src/core/actions/cityactions/GrowForest.java, src/core/game/Game.java, src/core/game/GameState.java, src/players/RandomAgent.java
Two bug fixes:
- existAvailableActions returning the actual value it should.
- GrowForest accessing tribe in execute with an actual tribe ID.
=> New random agent

src/core/actions/cityactions/Build.java, src/core/actors/Building.java, src/core/actors/Temple.java, src/players/RandomAgent.java
plus some debug code removed in random agent
=> What the branch name says

src/Play.java
This reverts commit 371edc8a71411569642829b57e81e4c9469128f0.
=> Revert "Update Play.java"

src/core/Types.java, src/core/actions/unitactions/Upgrade.java, src/core/game/Game.java
isFeasible using TribesConfig was unsafe, it should use UNIT.getCost()... which was also wrong for SHIP unit type.
=> Upgrade was spending more than it should for upgrading to Ship

src/Play.java, src/Run.java, src/core/actors/City.java, src/core/actors/Tribe.java, src/core/game/Board.java, src/core/game/Game.java, src/core/game/GameState.java
Tribes now lose if they have no cities.
Also, tribes that lost are not asked for actions anymore.
=> GameEnd management

src/core/actions/tribeactions/EndTurn.java, src/core/actions/unitactions/factory/MoveFactory.java, src/core/game/Board.java, src/core/game/Game.java, src/core/game/GameState.java, src/players/heuristics/TribesSimpleHeuristic.java, src/players/mc/MonteCarloAgent.java, src/players/osla/OneStepLookAheadAgent.java
Heuristic gives boost on game won/lost
Also some bugs:
- MoveFactory now checks there's nothing at destination
- EndTurn returns true now if execution was possible
=> next refactored

src/core/actions/unitactions/factory/UnitActionBuilder.java, src/core/game/Board.java
Battleship view range set to 2
=> Upgrade available when unit is finished

src/core/TribesConfig.java, src/core/actors/Tribe.java, src/core/game/Game.java
Also refactored GUI Full Obs. view into TribesConfig
=> Enabling playing with full observability.

src/core/levelgen/LevelGenerator.java
Ruins, capital placement and water chequering fixed
=> Level gen fixes

src/Play.java, src/core/actions/cityactions/Build.java, src/core/actions/unitactions/Examine.java, src/core/actions/unitactions/Upgrade.java
1) Lumber huts remove the forest in the tile.
2) Upgrade a naval unit does not ends the unit's turn.
3) A ruins spawning a superunit now removes the ruins resource
=> Mix bugfix

src/core/TribesConfig.java, src/core/Types.java, src/core/actions/unitactions/Attack.java, src/core/actions/unitactions/command/AttackCommand.java, src/utils/GameView.java
- DefenceForce x TribesConfig.DEFENCE_IN_WALLS if defender within city walls.
- DefenceForce x TribesConfig.DEFENCE_BONUS if defender:
* in city tile, with no walls, and unit has the Fortify ability.
* in water tile and Aquatism is researched.
* in forest tile if Archery is researched.
* in mountain tile if Meditation is researched.
Also, all logic functions from the Attack action moved to the Command class
=> Defence bonus set for defender where given by technologies.

src/Run.java, src/core/TribesConfig.java, src/core/Types.java, src/core/actions/tribeactions/command/ResearchTechCommand.java, src/core/actors/Tribe.java, src/core/game/Board.java, src/core/game/GameState.java, src/core/game/LevelLoader.java
Also, some scores weren't added before:
- score when researching a technology
- score when receiving a new city centre from start and village
=> intial scores no longer hardcoded, but computed.
